#!/usr/bin/env bash
set -euo pipefail
system=$(nix eval --raw --impure --expr builtins.currentSystem)
# pre-commit runs in its own CI job.
nix eval --json ".#checks.$system" --apply builtins.attrNames | \
  jq -r '.[] | select(. != "pre-commit")' | \
  xargs -P0 -I '{}' sh -c "nix build -L .#checks.$system.{} || { echo 'FAILED: \033[0;31mnix build -L .#checks.$system.{}\\033[0m'; kill 0; }"
